// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Media struct {
	Path            string          `json:"path"`
	Title           sql.NullString  `json:"title"`
	Duration        sql.NullInt64   `json:"duration"`
	Size            sql.NullInt64   `json:"size"`
	TimeCreated     sql.NullInt64   `json:"time_created"`
	TimeModified    sql.NullInt64   `json:"time_modified"`
	TimeDeleted     sql.NullInt64   `json:"time_deleted"`
	TimeFirstPlayed sql.NullInt64   `json:"time_first_played"`
	TimeLastPlayed  sql.NullInt64   `json:"time_last_played"`
	PlayCount       sql.NullInt64   `json:"play_count"`
	Playhead        sql.NullInt64   `json:"playhead"`
	Type            sql.NullString  `json:"type"`
	Width           sql.NullInt64   `json:"width"`
	Height          sql.NullInt64   `json:"height"`
	Fps             sql.NullFloat64 `json:"fps"`
	VideoCodecs     sql.NullString  `json:"video_codecs"`
	AudioCodecs     sql.NullString  `json:"audio_codecs"`
	SubtitleCodecs  sql.NullString  `json:"subtitle_codecs"`
	VideoCount      sql.NullInt64   `json:"video_count"`
	AudioCount      sql.NullInt64   `json:"audio_count"`
	SubtitleCount   sql.NullInt64   `json:"subtitle_count"`
}

type MediaFts struct {
	Path  string `json:"path"`
	Title string `json:"title"`
}
