// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Captions struct {
	MediaPath string          `json:"media_path"`
	Time      sql.NullFloat64 `json:"time"`
	Text      sql.NullString  `json:"text"`
}

type CaptionsFts struct {
	MediaPath string `json:"media_path"`
	Text      string `json:"text"`
}

type History struct {
	ID         int64         `json:"id"`
	MediaPath  string        `json:"media_path"`
	TimePlayed sql.NullInt64 `json:"time_played"`
	Playhead   sql.NullInt64 `json:"playhead"`
	Done       sql.NullInt64 `json:"done"`
}

type Media struct {
	Path            string          `json:"path"`
	Title           sql.NullString  `json:"title"`
	Duration        sql.NullInt64   `json:"duration"`
	Size            sql.NullInt64   `json:"size"`
	TimeCreated     sql.NullInt64   `json:"time_created"`
	TimeModified    sql.NullInt64   `json:"time_modified"`
	TimeDeleted     sql.NullInt64   `json:"time_deleted"`
	TimeFirstPlayed sql.NullInt64   `json:"time_first_played"`
	TimeLastPlayed  sql.NullInt64   `json:"time_last_played"`
	PlayCount       sql.NullInt64   `json:"play_count"`
	Playhead        sql.NullInt64   `json:"playhead"`
	Type            sql.NullString  `json:"type"`
	Width           sql.NullInt64   `json:"width"`
	Height          sql.NullInt64   `json:"height"`
	Fps             sql.NullFloat64 `json:"fps"`
	VideoCodecs     sql.NullString  `json:"video_codecs"`
	AudioCodecs     sql.NullString  `json:"audio_codecs"`
	SubtitleCodecs  sql.NullString  `json:"subtitle_codecs"`
	VideoCount      sql.NullInt64   `json:"video_count"`
	AudioCount      sql.NullInt64   `json:"audio_count"`
	SubtitleCount   sql.NullInt64   `json:"subtitle_count"`
	Album           sql.NullString  `json:"album"`
	Artist          sql.NullString  `json:"artist"`
	Genre           sql.NullString  `json:"genre"`
	Mood            sql.NullString  `json:"mood"`
	Bpm             sql.NullInt64   `json:"bpm"`
	Key             sql.NullString  `json:"key"`
	Decade          sql.NullString  `json:"decade"`
	Categories      sql.NullString  `json:"categories"`
	City            sql.NullString  `json:"city"`
	Country         sql.NullString  `json:"country"`
	Description     sql.NullString  `json:"description"`
	Language        sql.NullString  `json:"language"`
	Webpath         sql.NullString  `json:"webpath"`
	Uploader        sql.NullString  `json:"uploader"`
	TimeUploaded    sql.NullInt64   `json:"time_uploaded"`
	TimeDownloaded  sql.NullInt64   `json:"time_downloaded"`
	ViewCount       sql.NullInt64   `json:"view_count"`
	NumComments     sql.NullInt64   `json:"num_comments"`
	FavoriteCount   sql.NullInt64   `json:"favorite_count"`
	Score           sql.NullFloat64 `json:"score"`
	UpvoteRatio     sql.NullFloat64 `json:"upvote_ratio"`
	Latitude        sql.NullFloat64 `json:"latitude"`
	Longitude       sql.NullFloat64 `json:"longitude"`
}

type MediaFts struct {
	Path  string `json:"path"`
	Title string `json:"title"`
}

type Playlists struct {
	ID              int64          `json:"id"`
	Path            sql.NullString `json:"path"`
	ExtractorKey    sql.NullString `json:"extractor_key"`
	ExtractorConfig sql.NullString `json:"extractor_config"`
	TimeDeleted     sql.NullInt64  `json:"time_deleted"`
}
