// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddPlaylistItem(ctx context.Context, arg AddPlaylistItemParams) error
	ClearPlaylist(ctx context.Context, playlistID int64) error
	DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) error
	GetAllMediaMetadata(ctx context.Context) ([]GetAllMediaMetadataRow, error)
	GetCategoryStats(ctx context.Context) ([]GetCategoryStatsRow, error)
	GetCustomCategories(ctx context.Context) ([]string, error)
	GetGenreStats(ctx context.Context) ([]GetGenreStatsRow, error)
	GetHistoryCount(ctx context.Context, mediaPath string) (int64, error)
	GetMedia(ctx context.Context, limit int64) ([]Media, error)
	GetMediaByDuration(ctx context.Context, arg GetMediaByDurationParams) ([]Media, error)
	GetMediaByPath(ctx context.Context, arg GetMediaByPathParams) ([]Media, error)
	GetMediaByPathExact(ctx context.Context, path string) (Media, error)
	GetMediaByPlayCount(ctx context.Context, arg GetMediaByPlayCountParams) ([]Media, error)
	GetMediaBySize(ctx context.Context, arg GetMediaBySizeParams) ([]Media, error)
	GetMediaByType(ctx context.Context, arg GetMediaByTypeParams) ([]Media, error)
	GetPlaylistItems(ctx context.Context, playlistID int64) ([]GetPlaylistItemsRow, error)
	GetPlaylists(ctx context.Context) ([]Playlists, error)
	GetRandomMedia(ctx context.Context, limit int64) ([]Media, error)
	GetRatingStats(ctx context.Context) ([]GetRatingStatsRow, error)
	GetSiblingMedia(ctx context.Context, arg GetSiblingMediaParams) ([]Media, error)
	GetStats(ctx context.Context) (GetStatsRow, error)
	GetStatsByType(ctx context.Context) ([]GetStatsByTypeRow, error)
	GetUnfinishedMedia(ctx context.Context, limit int64) ([]Media, error)
	GetUnwatchedMedia(ctx context.Context, limit int64) ([]Media, error)
	GetUsedCategories(ctx context.Context) ([]GetUsedCategoriesRow, error)
	GetWatchedMedia(ctx context.Context, limit int64) ([]Media, error)
	InsertCaption(ctx context.Context, arg InsertCaptionParams) error
	InsertHistory(ctx context.Context, arg InsertHistoryParams) error
	InsertPlaylist(ctx context.Context, arg InsertPlaylistParams) (int64, error)
	MarkDeleted(ctx context.Context, arg MarkDeletedParams) error
	RemovePlaylistItem(ctx context.Context, arg RemovePlaylistItemParams) error
	SearchCaptions(ctx context.Context, query string) ([]SearchCaptionsRow, error)
	SearchMediaFTS(ctx context.Context, arg SearchMediaFTSParams) ([]Media, error)
	UpdateMediaCategories(ctx context.Context, arg UpdateMediaCategoriesParams) error
	UpdatePath(ctx context.Context, arg UpdatePathParams) error
	UpdatePlayHistory(ctx context.Context, arg UpdatePlayHistoryParams) error
	UpsertMedia(ctx context.Context, arg UpsertMediaParams) error
}

var _ Querier = (*Queries)(nil)
